name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        toolchain:
          - stable
          # minimum version: because of "time"
          - "1.67"

    steps:

      - uses: actions/checkout@v4

      - name: Install Rust ${{ matrix.toolchain }}
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --component rustfmt,clippy --target wasm32-unknown-unknown
          rustup default ${{ matrix.toolchain }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Run cargo fmt
        run: |
          cargo fmt --all -- --check

      - name: Run cargo check
        run: |
          cargo check

      - name: Run cargo test
        run: |
          cargo test

      - name: Run cargo clippy
        run: |
          cargo clippy -- -D warnings
